//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHKPlayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".avi;.mp4")]
        public string folder_supportedVideo {
            get {
                return ((string)(this["folder_supportedVideo"]));
            }
            set {
                this["folder_supportedVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".mp3")]
        public string folder_supportedAudio {
            get {
                return ((string)(this["folder_supportedAudio"]));
            }
            set {
                this["folder_supportedAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".png;")]
        public string folder_supportedPicture {
            get {
                return ((string)(this["folder_supportedPicture"]));
            }
            set {
                this["folder_supportedPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string folder_root {
            get {
                return ((string)(this["folder_root"]));
            }
            set {
                this["folder_root"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spillervideostat")]
        public string folder_playerStatPictureFolder {
            get {
                return ((string)(this["folder_playerStatPictureFolder"]));
            }
            set {
                this["folder_playerStatPictureFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spiller")]
        public string folder_playerPictureFolder {
            get {
                return ((string)(this["folder_playerPictureFolder"]));
            }
            set {
                this["folder_playerPictureFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spillervideo")]
        public string folder_playerVideoFolder {
            get {
                return ((string)(this["folder_playerVideoFolder"]));
            }
            set {
                this["folder_playerVideoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spillervideostat\\video")]
        public string folder_playerStatVideoFolder {
            get {
                return ((string)(this["folder_playerStatVideoFolder"]));
            }
            set {
                this["folder_playerStatVideoFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spillervideostat\\mp3")]
        public string folder_playerStatMusicFolder {
            get {
                return ((string)(this["folder_playerStatMusicFolder"]));
            }
            set {
                this["folder_playerStatMusicFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string folder_ignore {
            get {
                return ((string)(this["folder_ignore"]));
            }
            set {
                this["folder_ignore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Marcus\\Documents\\GitHub\\VHKPlayer\\DigiMatch")]
        public string folder_playerStatisticInformation {
            get {
                return ((string)(this["folder_playerStatisticInformation"]));
            }
            set {
                this["folder_playerStatisticInformation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\musik\\andet;root\\musik\\langtmusik;root\\musik\\opvarmning;root\\musik\\pausemusi" +
            "k;root\\musik\\scor;root\\musik\\scorud;root\\musik\\spilstop;root\\musik\\stemning;root" +
            "\\musik\\timeout;root\\blandet;root\\superhero;root")]
        public string folder_playableFileFolders {
            get {
                return ((string)(this["folder_playableFileFolders"]));
            }
            set {
                this["folder_playableFileFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{RekFørKamp;root\\Rek;false;1;Sorted;AllFiles},{RekHalvej1;root\\Rek;false;2;Sorted" +
            ";AllFiles},{10Sek;root\\10Sek;false;0;Folder;Iterated}")]
        public string folder_playlists {
            get {
                return ((string)(this["folder_playlists"]));
            }
            set {
                this["folder_playlists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xml;txt")]
        public string folder_supportedInfoFile {
            get {
                return ((string)(this["folder_supportedInfoFile"]));
            }
            set {
                this["folder_supportedInfoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10Sek")]
        public string application_autoPlaylist {
            get {
                return ((string)(this["application_autoPlaylist"]));
            }
            set {
                this["application_autoPlaylist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Andet;(folder path:\"root\\musik\\andet\");SingleFile},{Opvarmning;(folder path:\"roo" +
            "t\\musik\\Opvarmning\");SingleFile}")]
        public string application_leftBlockTabs {
            get {
                return ((string)(this["application_leftBlockTabs"]));
            }
            set {
                this["application_leftBlockTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string application_duringMatchTabs {
            get {
                return ((string)(this["application_duringMatchTabs"]));
            }
            set {
                this["application_duringMatchTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string application_duringMatchRightContent {
            get {
                return ((string)(this["application_duringMatchRightContent"]));
            }
            set {
                this["application_duringMatchRightContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string application_rightBlockTabs {
            get {
                return ((string)(this["application_rightBlockTabs"]));
            }
            set {
                this["application_rightBlockTabs"] = value;
            }
        }
    }
}
