//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHKPlayer.Utility {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class FolderProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static FolderProperties defaultInstance = ((FolderProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FolderProperties())));
        
        public static FolderProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".mp3")]
        public string supportedMusic {
            get {
                return ((string)(this["supportedMusic"]));
            }
            set {
                this["supportedMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".png;.jpeg")]
        public string supportedPicture {
            get {
                return ((string)(this["supportedPicture"]));
            }
            set {
                this["supportedPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".avi")]
        public string supportedVideo {
            get {
                return ((string)(this["supportedVideo"]));
            }
            set {
                this["supportedVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".xml")]
        public string supportedInfo {
            get {
                return ((string)(this["supportedInfo"]));
            }
            set {
                this["supportedInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\10sek;root\\spiller;root\\musik")]
        public string requiredFolders {
            get {
                return ((string)(this["requiredFolders"]));
            }
            set {
                this["requiredFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Marcus\\Dropbox\\Programmering\\C#\\vhk")]
        public string root {
            get {
                return ((string)(this["root"]));
            }
            set {
                this["root"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spiller")]
        public string playerFolderPicture {
            get {
                return ((string)(this["playerFolderPicture"]));
            }
            set {
                this["playerFolderPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spillervideo")]
        public string playerFolderVideo {
            get {
                return ((string)(this["playerFolderVideo"]));
            }
            set {
                this["playerFolderVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spillervideostat")]
        public string playerFolderStatPicture {
            get {
                return ((string)(this["playerFolderStatPicture"]));
            }
            set {
                this["playerFolderStatPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spillervideostat\\video")]
        public string playerFolderStatVideo {
            get {
                return ((string)(this["playerFolderStatVideo"]));
            }
            set {
                this["playerFolderStatVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root\\spillervideostat\\mp3")]
        public string playerFolderStatMusic {
            get {
                return ((string)(this["playerFolderStatMusic"]));
            }
            set {
                this["playerFolderStatMusic"] = value;
            }
        }
    }
}
